name: Chat-Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'geochat-chat-service/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'geochat-chat-service/**'

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./geochat-chat-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/geochat-chat-service:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/geochat-chat-service:latest 